trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'service_connection'
    azureContainerRegistry: '{"loginServer":"acrdockerpushpocdevops.azurecr.io", "id" : "/subscriptions/ff19a5b8-ab83-4fd1-b00b-010252464cac/resourceGroups/acrdockerpush/providers/Microsoft.ContainerRegistry/registries/acrdockerpushpocdevops"}'
    dockerComposeFile: 'docker-compose.yml'
    projectName: 'projectcompliance'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up -d'
    currentWorkingDirectory: 