apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: common-workspacev1
  name: common-workspacev1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
